### ISSUE TITLE
Termux使用报错

### ISSUE THREAD

**Issue by danicaStarR** [MZhao-ouo/CMDGPT#5]
系统：Android (arm)
Python 版本:3.8.x

```
$ cmdgpt
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/cmdgpt", line 6, in <module>
    from cmdgpt.main import main
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cmdgpt/main.py", line 2, in <module>
    from .presets import *
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cmdgpt/presets.py", line 41, in <module>
    cmd_history = get_cmd_history(current_shell, user_home)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cmdgpt/utils.py", line 63, in get_cmd_history
    with open(history_filename, "rt", errors="ignore") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.bash_history'
```

**Comment by MZhao-ouo** [comment]
你创建一个.bash_history文件吧。在用户根目录执行`touch .bash_history`
